src/ContosoAssets.WebApp/Areas/SubscriptionManagement/Controllers/UsersController.cs
using System;
using System.Threading.Tasks;
using ContosoAssets.SolutionManagement.CustomerManagement;
using ContosoAssets.SolutionManagement.Data;
using ContosoAssets.Utils;
using ContosoAssets.WebApp.Areas.SubscriptionManagement.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace ContosoAssets.WebApp.Areas.SubscriptionManagement.Controllers
{
    [Area("SubscriptionManagement")]
    // See https://github.com/aspnet/AspNetCore/blob/master/src/Identity/Core/src/IdentityConstants.cs#L15
    [Authorize(Roles = Constants.CustomerAdminRoleName, AuthenticationSchemes = "Identity.Application")]
    public class UsersController : Controller
    {
        private readonly ICustomerManager customerManagementStore;
        private readonly ILogger<UsersController> logger;
        private readonly IUserManagerAdapter userManager;

        public UsersController(ICustomerManager customerManagementStore, IUserManagerAdapter userManager,
            ILogger<UsersController> logger)
        {
            this.customerManagementStore = customerManagementStore;
            this.userManager = userManager;
            this.logger = logger;
        }

        // GET: CustomerUsers/Home/Create
        public IActionResult Create()
        {
            var createUserModel = new CustomerUserModel
            {
                CustomerName = this.User.Identity.Name.GetDomainNameFromEmail(), CustomerUserName = ""
            };
            return this.View(createUserModel);
        }

        // POST: CustomerUsers/Home/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromForm] CustomerUserModel user)
        {
            var userName = $"{user.CustomerUserName.Trim()}@{user.CustomerName.Trim()}";

            CustomerUser customerUser = null;
            if (this.ModelState.IsValid && userName.IsValidEmail())
            {
                // Only add user if it is the same domain name
                if (this.User.Identity.Name.GetDomainNameFromEmail()
                    == userName.GetDomainNameFromEmail())
                {
                    customerUser = new CustomerUser
                    {
                        UserName = userName,
                        CreatedDate = DateTimeOffset.UtcNow,
                        Id = Guid.NewGuid(),
                        CustomerName = this.User.Identity.Name.GetDomainNameFromEmail()
                    };

                    // Only the admin can land here, and admin's name is the email.
                    // We assume the customer name is  the email domain
                    _ = await this.customerManagementStore.AddUserAsync(customerUser);

                    return this.RedirectToAction(nameof(this.Index));
                }
            }

            this.ModelState.AddModelError("Username", "User name is not a valid email.");
            return this.View(customerUser);
        }

        // GET: CustomerUsers/Home/Delete/5
        public async Task<IActionResult> Delete(Guid id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var customerUser = await this.customerManagementStore.GetCustomerUserByIdAsync(id);

            if (customerUser == null)
            {
                return this.NotFound();
            }

            return this.View(customerUser);
        }

        // POST: CustomerUsers/Home/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var customerUser = await this.customerManagementStore.GetCustomerUserByIdAsync(id);
            if (await this.customerManagementStore.DeleteCustomerUserAsync(customerUser) ==
                SolutionManagerOperationResult.Success)
            {
                await this.userManager.DeleteUserAsync(customerUser.UserName);
            }

            return this.RedirectToAction(nameof(this.Index));
        }

        // GET: CustomerUsers/Home/Details/5
        public async Task<IActionResult> Details(Guid id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var customerUser = await this.customerManagementStore.GetCustomerUserByIdAsync(id);

            if (customerUser == null)
            {
                return this.NotFound();
            }

            return this.View(customerUser);
        }

        // GET: CustomerUsers/Home/Edit/5
        public async Task<IActionResult> Edit(Guid id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var customerUser = await this.customerManagementStore.GetCustomerUserByIdAsync(id);

            if (customerUser == null)
            {
                return this.NotFound();
            }

            return this.View(customerUser);
        }

        // POST: CustomerUsers/Home/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("UserName,CustomerName,CreatedDate,Id")]
            CustomerUser customerUser)
        {
            if (id != customerUser.Id)
            {
                return this.NotFound();
            }

            if (this.ModelState.IsValid)
            {
                try
                {
                    await this.customerManagementStore.UpdateCustomerUserAsync(customerUser);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await this.CustomerUserExists(customerUser.UserName))
                    {
                        return this.NotFound();
                    }

                    throw;
                }

                return this.RedirectToAction(nameof(this.Index));
            }

            return this.View(customerUser);
        }

        // GET: CustomerUsers/Home
        public async Task<IActionResult> Index()
        {
            return this.View(await this.customerManagementStore.GetCustomerUsersWithUsageAsync(
                this.User.Identity.Name.GetDomainNameFromEmail()));
        }

        private async Task<bool> CustomerUserExists(string email)
        {
            return await this.customerManagementStore.CustomerUserExistsByUserNameAsync(email);
        }
    }
}

src/ContosoAssets.WebApp/Controllers/AssetsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using ContosoAssets.SolutionManagement.SubscriptionManagement;
using ContosoAssets.Utils;
using ContosoAssets.WebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ContosoAssets.WebApp.Controllers
{
    // See https://github.com/aspnet/AspNetCore/blob/master/src/Identity/Core/src/IdentityConstants.cs#L15
    [Authorize(Roles = Constants.CustomerUserRoleName, AuthenticationSchemes = "Identity.Application")]
    public class AssetsController : MeteredController
    {
        private const string upsellMessage =
            "Usage is over selected product plan limits. Please contact your administrator to upgrade.";

        private readonly AssetManagementDbContext _context;

        public AssetsController(AssetManagementDbContext context, ISubscriptionManager skuManager) : base(skuManager)
        {
            this._context = context;
        }

        // GET: Assets/Create
        public IActionResult Create()
        {
            return this.View();
        }

        // POST: Assets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,LastUpdateTime,Status")]
            Asset asset)
        {
            if (!await this.CheckLimitAndMeter())
            {
                this.ModelState.AddModelError("Usage", upsellMessage);
                return this.View("AddAssetError");
            }

            if (this.ModelState.IsValid)
            {
                asset.LastUpdateTime = DateTimeOffset.UtcNow;
                asset.CustomerName = this.User.Identity.Name.GetDomainNameFromEmail();
                asset.Id = Guid.NewGuid().ToString();
                this._context.Add(asset);
                await this._context.SaveChangesAsync();
                return this.RedirectToAction(nameof(this.Index));
            }

            return this.View(asset);
        }

        // GET: Assets/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var asset = await this._context.Assets
                .FirstOrDefaultAsync(m => m.Id == id);
            if (asset == null)
            {
                return this.NotFound();
            }

            return this.View(asset);
        }

        // POST: Assets/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            await this.CheckLimitAndMeter();

            var asset = await this._context.Assets.FindAsync(id);
            this._context.Assets.Remove(asset);
            await this._context.SaveChangesAsync();
            return this.RedirectToAction(nameof(this.Index));
        }

        // GET: Assets/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var asset = await this._context.Assets
                .FirstOrDefaultAsync(m => m.Id == id);
            if (asset == null)
            {
                return this.NotFound();
            }

            return this.View(asset);
        }

        // GET: Assets/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var asset = await this._context.Assets.FindAsync(id);
            if (asset == null)
            {
                return this.NotFound();
            }

            return this.View(asset);
        }

        // POST: Assets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Name,LastUpdateTime,Status")]
            Asset asset)
        {
            if (!await this.CheckLimitAndMeter())
            {
                this.ModelState.AddModelError("Usage", upsellMessage);
                return this.View(asset);
            }

            if (id != asset.Id)
            {
                return this.NotFound();
            }

            if (this.ModelState.IsValid)
            {
                try
                {
                    var existingAsset = await this._context.Assets.FirstOrDefaultAsync(a => a.Id == asset.Id);

                    if (existingAsset != default(Asset))
                    {
                        existingAsset.LastUpdateTime = DateTimeOffset.UtcNow;
                        existingAsset.Status = asset.Status;

                        this._context.Update(existingAsset);
                        await this._context.SaveChangesAsync();
                    }
                    else
                    {
                        return this.NotFound();
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!this.AssetExists(asset.Id))
                    {
                        return this.NotFound();
                    }

                    throw;
                }

                return this.RedirectToAction(nameof(this.Index));
            }

            return this.View(asset);
        }

        // GET: Assets
        public async Task<IActionResult> Index()
        {
            return this.View(await this._context.Assets
                .Where(a => a.CustomerName == this.User.Identity.Name.GetDomainNameFromEmail()).ToListAsync());
        }

        private bool AssetExists(string id)
        {
            return this._context.Assets.Any(e => e.Id == id);
        }
    }
}

src/ContosoAssets.WebApp/Views/Shared/_Layout.cshtml
@using ContosoAssets.SolutionManagement
@using ContosoAssets.SolutionManagement.SubscriptionManagement
@using ContosoAssets.Utils
@using Microsoft.AspNetCore.Identity
@inject UserManager<IdentityUser> UserManager
@inject SignInManager<IdentityUser> SignInManager
@inject ISubscriptionManager subscriptionManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Contoso Assets</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Contoso Assets</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <partial name="_LoginPartial.cshtml"/>
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>

                    @if (SignInManager.IsSignedIn(User) && UserManager.IsUserInRole(User, Constants.CustomerUserRoleName))
                    {
                        @if (UserManager.IsUserSubscriptionActive(User, subscriptionManager))
                         {
                             <li class="nav-item">
                                 <a id="manageUsers" class="nav-link text-dark" asp-controller="Assets" asp-action="Index" title="Assets">Assets</a>
                             </li>
                         }
                    }

                    @if (UserManager.IsUserInRole(User, Constants.CustomerAdminRoleName))
                    {
                        <li class="nav-item">
                            <a id="manageUsers" class="nav-link text-dark" asp-area="SubscriptionManagement" asp-controller="Users" asp-action="Index" title="ManageUsers">Manage users</a>
                        </li>
                        <li class="nav-item">
                            <a id="manageSubscription" class="nav-link text-dark" asp-area="SubscriptionManagement" asp-controller="Subscription" asp-action="Edit" title="Manage subscription">Subscription details</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <partial name="_CookieConsentPartial"/>
    <main role="main" class="pb-3">
        @if (SignInManager.IsSignedIn(User) && UserManager.IsUserInRole(User, Constants.CustomerUserRoleName) && !UserManager.IsUserSubscriptionActive(User, subscriptionManager))
        {
            <div class="alert alert-danger" role="alert">
                Subscription is not active, please contact your administrator.
            </div>
        }

        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2019 - Contoso Assets
    </div>
</footer>

<environment include="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
</environment>
<environment exclude="Development">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
    </script>
</environment>
<script src="~/js/site.js" asp-append-version="true"></script>

@RenderSection("Scripts", false)
</body>
</html>